# Generated by Django 5.2.9 on 2026-01-03 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('icon', models.CharField(blank=True, default='📁', max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Couleur')),
                ('type', models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense'), ('both', 'Les deux')], default='expense', max_length=10, verbose_name='Type')),
                ('is_system', models.BooleanField(default=False, verbose_name='Catégorie système')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('type', models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense')], max_length=10, verbose_name='Type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Récurrente')),
                ('recurring_config', models.JSONField(blank=True, help_text='\n        Format JSON:\n        {\n            "frequency": "monthly",  // daily, weekly, monthly, yearly\n            "interval": 1,           // tous les X périodes\n            "end_date": "2025-12-31", // nullable = infini\n            "day_of_month": 15       // pour monthly\n        }\n        ', null=True, verbose_name='Configuration de récurrence')),
                ('attachment', models.URLField(blank=True, max_length=500, null=True, verbose_name='Pièce jointe')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finances.category', verbose_name='Catégorie')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='groups.group', verbose_name='Groupe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='finances.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Partage de dépense',
                'verbose_name_plural': 'Partages de dépenses',
                'db_table': 'expense_splits',
                'ordering': ['transaction', 'user'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='categories_user_id_418e53_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_system'], name='categories_is_syst_2704b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_059bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['group', 'date'], name='transaction_group_i_1bb84a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_bf503b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'date'], name='transaction_type_aaad3a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type', 'date'], name='transaction_user_id_3860f0_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesplit',
            index=models.Index(fields=['transaction'], name='expense_spl_transac_3f263a_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesplit',
            index=models.Index(fields=['user', 'is_paid'], name='expense_spl_user_id_f85fd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensesplit',
            constraint=models.UniqueConstraint(fields=('transaction', 'user'), name='unique_split_per_user'),
        ),
    ]
