# Generated by Django 5.2.9 on 2026-01-12 07:15

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget mensuel alloué à cette catégorie', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget mensuel'),
        ),
        migrations.AddField(
            model_name='category',
            name='budget_alert_threshold',
            field=models.IntegerField(default=80, help_text='Pourcentage du budget à partir duquel une alerte est envoyée', validators=[django.core.validators.MinValueValidator(0)], verbose_name="Seuil d'alerte (%)"),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de la catégorie', null=True, verbose_name='Description'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['budget'], name='categories_budget_c0c377_idx'),
        ),
    ]
