# Generated by Django 5.2.9 on 2026-01-03 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image')),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('GBP', 'Livre Sterling (£)'), ('CHF', 'Franc Suisse (CHF)'), ('CAD', 'Dollar Canadien (CA$)'), ('XAF', 'Franc CFA CEMAC (FCFA)'), ('XOF', 'Franc CFA UEMOA (CFA)')], default='EUR', max_length=3, verbose_name='Devise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name="Email de l'invité")),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('declined', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=10, verbose_name='Statut')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group', verbose_name='Groupe')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
            ],
            options={
                'verbose_name': 'Invitation de groupe',
                'verbose_name_plural': 'Invitations de groupe',
                'db_table': 'group_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('member', 'Membre')], default='member', max_length=10, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('left', 'Parti')], default='pending', max_length=10, verbose_name='Statut')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'adhésion")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group', verbose_name='Groupe')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre du groupe',
                'verbose_name_plural': 'Membres du groupe',
                'db_table': 'group_members',
                'ordering': ['group', '-role', 'joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['owner'], name='groups_owner_i_aea863_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='groups_is_acti_c63b73_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['token'], name='group_invit_token_58add1_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['email', 'status'], name='group_invit_email_1a7c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['group', 'status'], name='group_invit_group_i_66b8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'status'], name='group_membe_group_i_09ad0d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user', 'status'], name='group_membe_user_id_942afd_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_member_per_group'),
        ),
    ]
