# Generated by Django 5.2.9 on 2026-01-03 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='Journée entière')),
                ('color', models.CharField(choices=[('#3B82F6', 'Bleu'), ('#EF4444', 'Rouge'), ('#10B981', 'Vert'), ('#F59E0B', 'Orange'), ('#8B5CF6', 'Violet'), ('#EC4899', 'Rose'), ('#14B8A6', 'Turquoise'), ('#6B7280', 'Gris')], default='#3B82F6', max_length=7, verbose_name='Couleur')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='reminders.reminder', verbose_name='Rappel lié')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='finances.transaction', verbose_name='Transaction liée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'events',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['user', 'start_date'], name='events_user_id_07dc33_idx'), models.Index(fields=['start_date', 'end_date'], name='events_start_d_92ba55_idx')],
            },
        ),
    ]
