# Generated by Django 5.2.9 on 2026-01-03 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('in_app', 'In-App')], default='email', max_length=10, verbose_name='Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('related_type', models.CharField(blank=True, max_length=50, null=True, verbose_name="Type d'objet lié")),
                ('related_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'objet lié")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('failed', 'Échec')], default='pending', max_length=10, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log de notification',
                'verbose_name_plural': 'Logs de notifications',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_9d8bc4_idx'), models.Index(fields=['type', 'status'], name='notificatio_type_c2a750_idx'), models.Index(fields=['related_type', 'related_id'], name='notificatio_related_148759_idx')],
            },
        ),
    ]
