# Generated by Django 5.2.9 on 2026-01-13 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA CEMAC (FCFA)'), ('XOF', 'Franc CFA UEMOA (CFA)'), ('EUR', 'Euro (€)'), ('USD', 'Dollar US ($)'), ('GBP', 'Livre Sterling (£)'), ('CHF', 'Franc Suisse (CHF)'), ('CAD', 'Dollar Canadien (CA$)')], default='XAF', max_length=3, verbose_name='Devise préférée')),
                ('avatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='Avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès administration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('purpose', models.CharField(choices=[('registration', 'Inscription'), ('login', 'Connexion'), ('password_reset', 'Réinitialisation mot de passe'), ('email_change', 'Changement email')], max_length=20, verbose_name='Objectif')),
                ('attempts', models.IntegerField(default=0, verbose_name='Tentatives')),
                ('max_attempts', models.IntegerField(default=5, verbose_name='Max tentatives')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de vérification',
                'verbose_name_plural': 'Codes de vérification',
                'db_table': 'email_verification_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_reminders', models.BooleanField(default=True, verbose_name='Rappels par email')),
                ('email_weekly_summary', models.BooleanField(default=True, verbose_name='Résumé hebdomadaire')),
                ('email_group_activity', models.BooleanField(default=True, verbose_name='Activité des groupes')),
                ('email_budget_alerts', models.BooleanField(default=True, verbose_name='Alertes budget')),
                ('email_payment_notifications', models.BooleanField(default=True, verbose_name='Notifications paiement')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='Notifications push')),
                ('reminder_time', models.TimeField(default='09:00:00', verbose_name='Heure des rappels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de réinitialisation',
                'verbose_name_plural': 'Tokens de réinitialisation',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='email_verif_email_26176b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['code', 'email'], name='email_verif_code_4d7b95_idx'),
        ),
    ]
