# Generated by Django 5.2.9 on 2026-01-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_monthly_summary',
            field=models.BooleanField(default=True),
        ),
    ]
