# Generated by Django 5.2.9 on 2026-01-03 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('reminder_type', models.CharField(choices=[('payment', 'Paiement dû'), ('bill', 'Facture'), ('general', 'Général')], default='general', max_length=10, verbose_name='Type')),
                ('reminder_date', models.DateTimeField(verbose_name='Date du rappel')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Récurrent')),
                ('recurring_config', models.JSONField(blank=True, help_text='\n        Format JSON:\n        {\n            "frequency": "monthly",  // daily, weekly, monthly, yearly\n            "interval": 1,           // tous les X périodes\n            "end_date": "2025-12-31", // nullable = infini\n            "day_of_month": 15       // pour monthly\n        }\n        ', null=True, verbose_name='Configuration de récurrence')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de notification")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='groups.group', verbose_name='Groupe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'db_table': 'reminders',
                'ordering': ['reminder_date'],
                'indexes': [models.Index(fields=['user', 'reminder_date'], name='reminders_user_id_f8e55c_idx'), models.Index(fields=['group', 'reminder_date'], name='reminders_group_i_99bd6b_idx'), models.Index(fields=['reminder_date', 'notification_sent'], name='reminders_reminde_4d4a8e_idx'), models.Index(fields=['is_completed', 'reminder_date'], name='reminders_is_comp_3afd3b_idx')],
            },
        ),
    ]
